SELECT PS.NAME_OF_SCHOOL, SD.COMMUNITY_AREA_NAME, PS.AVERAGE_STUDENT_ATTENDANCE
FROM chicago_public_schools PS
JOIN chicago_socioeconomic_data SD ON PS.COMMUNITY_AREA_NUMBER = SD.COMMUNITY_AREA_NUMBER
WHERE SD.HARDSHIP_INDEX = 98