SELECT C.CASE_NUMBER, C.PRIMARY_TYPE, SD.COMMUNITY_AREA_NAME
FROM chicago_crime C
JOIN chicago_socioeconomic_data SD ON C.COMMUNITY_AREA_NUMBER = SD.COMMUNITY_AREA_NUMBER
WHERE LCASE(C.LOCATION_DESCRIPTION) LIKE '%school%'